name: Lighthouse Audit Loop

on:
  pull_request:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Start server
        run: pnpm start & sleep 5

      - name: Run Lighthouse Loop
        env:
          LH_OUT_DIR: .lighthouse
          LH_T_PERF: '90'
          LH_T_A11Y: '95'
          LH_T_SEO: '95'
          LH_T_BP: '95'
        run: pnpm audit:lh:loop -- http://localhost:3000/

      - name: Upload Lighthouse Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: .lighthouse


